name = "asrvtech"
main = "worker.js"
compatibility_date = "2026-04-22"

[assets]
binding = "ASSETS"
directory = "dist/public"

[vars]
CONTACT_TO_EMAIL = "customers@asrvtech.in"
CONTACT_FROM_NAME = "ASRV Tech"
RESEND_FROM = "ASRV Tech <customers@asrvtech.in>"
